#!/bin/bash
set -e

usage() {
    >&2 cat << EOF
Usage: spinstamp [options] FILE 

Add header and license information to a Spin object.

Options:
  -v, --version  Sets version of file.
  -c, --company  Sets company name to use in copyright.
  -h, --help     Displays this help.

Arguments:
  FILE           Spin file to stamp.
EOF
    exit 0
}

while [[ $# > 0 ]]
do
    ARG="$1"
    shift

    case $ARG in
        -v|--version)
            if [[ $# < 1 ]] ; then
                >&2 echo "Error: No version given; pass with '-v'"
                exit 1
            fi

            VERSION="$1"
            shift
            ;;

        -c|--company)
            if [[ $# < 1 ]] ; then
                >&2 echo "Error: No company given; pass with '-c'"
                exit 1
            fi

            COMPANY="$1"
            shift
            ;;

        -h|--help)
            usage
            ;;

        *)
            FILE="$ARG"
            ;;
    esac
done

if [ -z $VERSION ] ; then
        >&2 echo "Error: No version given; pass with '-v'"
        exit 1
fi

if [ -z $COMPANY ] ; then
        >&2 echo "Error: No company given; pass with '-c'"
        exit 1
fi

if [ -z $FILE ] ; then
        >&2 echo "Error: No Spin object given!"
        exit 1
fi

if [ ${FILE: -5} != ".spin" ] ; then
        >&2 echo "Error: File given not a Spin object!"
        exit 1
fi

F=`basename $FILE`

TODAY=`git log $F 2>/dev/null | head -3 | grep "Date" | awk '{print $6}'`
CREATED=`git log --reverse $F 2>/dev/null | head -3 | grep "Date" | awk '{print $6}'`

if [[ -z $TODAY ]] ; then
    AGE=`date +%Y`
elif  [[ ! $CREATED == $TODAY ]] ; then
    AGE=$CREATED-$TODAY
else
    AGE=$TODAY
fi

cat << EOF
' ${F}
' -------------------------------------------------
' Version: ${VERSION}
' Author(s): $(git blame ${FILE} -f \
  | cut -d'(' -f 2- \
  | sed -e 's/ [0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9] .*//g' \
  | sort \
  | uniq \
  | sed ':a;N;$!ba;s/\n/, /g')
' Copyright (c) ${AGE} ${COMPANY}
' See end of file for terms of use.
' -------------------------------------------------

`cat ${FILE}`

' --------------------------------------------------------------------------------------------------------
' TERMS OF USE: MIT License
'
' Permission is hereby granted, free of charge, to any person obtaining a copy of this software and
' associated documentation files (the "Software"), to deal in the Software without restriction, including
' without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
' copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the
' following conditions:
'
' The above copyright notice and this permission notice shall be included in all copies or substantial
' portions of the Software.
'
' THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT
' LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
' IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
' WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
' SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
' --------------------------------------------------------------------------------------------------------
EOF
